---
title: 'Wrap up'
number-sections: false
---

## Specific Tips

This section goes through some of the specific questions that members of the Imago team had before putting together this workshop.

### Dealing with Jupyter notebooks

This was covered a fair bit in [day2_merge_conflicts.qmd]. The best way is to:

- clear outputs
- don't work on the same cells as your colleagues
- don't use Jupyter notebooks for production code - use them for their intended purpose (training, demos)
- fixing them manually and overwriting the old file is often easier than trying to diff the JSON

There are tools for helping with Jupyter notebooks - e.g. one could use GitHub Actions to run `nbconvert` to clear outputs, [`nbdime`](https://github.com/jupyter/nbdime) can make merging easier. 
Prevention is better than cure however! 

### Creating a chapter in Quarto

The [repository used to create this webpage](https://github.com/Imago-SDRUK/github_training) is an example of this.

The key points are:

- Create directories for the different chapters 
- Upload the content in those chapters. e.g. 

```yaml
my-quarto-book/
├── quarto.yml
├── index.qmd
├── chapter1/
│   └── chapter1_content1.qmd
│   └── chapter1_content2.qmd
│   └── chapter1_index.qmd
├── chapter2/
│   └── chapter2_content.qmd
│   └── chapter2_index.qmd
├── chapter3/
│   └── chapter3_content.qmd
│   └── chapter2_index.qmd
│	└──assets/
│	   └──picture_1.png
```

Here we have `assets` (for e.g. images) inside the chapters rather than one big `assets` folder at the top level. 

- Update quarto.yml under the `book` section to include your chapters.
	- Then, if each chapter has several files (as in the case above - we have `content1` and `content2`),
	 we can nest them by creating new `index.qmd` for each chapter

```yaml 

chapters:
    - index.qmd

    - part: chapter1/chapter1_index.qmd
      chapters:
        - chapter1/chapter1_content1.qmd 
		- chapter1/chapter1_content2.qmd

    - part: chapter2/chapter2_index.qmd
		chapters:
		- chapter2/chapter2_content.qmd

	- part: chapter3/chapter3_index.qmd 
		chapters:
		- chapter3/chapter3_content.qmd
      
```

- Use relative links to link chapters together
	- e.g. from `chapter3_content.qmd`, you can link to `chapter2_content.qmd` like `(link text)[../chapter2/chapter2_content.qmd]`.

Have a look in the workshop repo if you want an example of this in action!
It has an example of a GH Actions workflow (in `.github/workflows/build_quarto.yml`) to automatically publish and update the site whenever a commit or PR is made into `main` - coming to a future workshop near you...

### How to cite effectively?

There are various ways. You can cite the GitHub repository itself if you don't have a data description paper. The best bet is to use something similar to [Zenodo](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content). 
The main consideration is that you need your repository to be **public** - but this should be the case anyway if you're citing it! 
You can also add a [neat little badge](https://gist.github.com/seignovert/ae6771f400ca464d294261f42900823a) to your `README.md` to link to the Zenodo page! 

For stuff that's more like tooling or methods, we could consider a submission to the [*Journal of Open Source Software*](https://joss.theoj.org/). 
This differs from a normal journal in that papers are usually ~2 pages long, and focus more on the software than the application.
Writing them is intended to be much simpler than a normal paper - the hard work is in developing the software itself! 

### Idle thoughts

- Don't worry about perfection straight away. Issues are where all your messy ideas can live. Worry about polish just before you're ready to merge it in - remember `main` is where things need to be polished. 
- Documentation is key! You're more likely to waste time/be stressed/want to quit academia when you can't remember how and why you did anything down the line (and neither can your colleagues) writing a paper than you will spending 10 minutes a day/week writing documentation and populating Issues. 
- These might seem like restrictive or time-consuming behaviours, but they are standard practice for software developers *for a reason* - because they work.
	- Software developers spend as much as possible trying to minimise the amount of work needing to be done so take heed their advice!
- If a PR is hard to review, it is probably too big - in which case it is better to split across multiple issues/PRs.
	- Not a particularly good heuristic for how big one should be - just make it as big as it needs to be but no bigger. The more moving parts there are the time it takes to review scales non-linearly! 
- Sharing code/putting it out for review, particularly as an academic rather than a software developer can seem daunting! But remember that these processes are there to make things better for everyone - this lets us all combine our strengths and learn things from one another.
	- Feel free to request an RSE reviewer as well as an academic colleague - even if we don't have time the worst we can do is say "no sorry"! 
- If you have questions or problems - reach out to the RSEs directly! Email, or there is an RSE page on Teams. 

- ***Don't worry if you don't follow all of the guidelines all of the time***! The intent is to improve the way we work, not to enforce orthodoxy for its own sake. 

## Heuristics 

- If you are doing work on something, it should have an Issue.
- `main` is a record, not a workspace
- Document your work in Issues, PR when ready, link to the Issue. 
- If a PR is hard to review, it’s too big - make the next one smaller! 
- Review intent before implementation.
- Non-critical changes should be suggestions not blockers.
- Perfect is the enemy of merged.
- Use your team - ask for help on both technical and conceptual problems! 

## Some example Issues and PRs:

https://github.com/Imago-SDRUK/Imago-web/issues/95 - using Issues to flag things that we want from our products 
https://github.com/Imago-SDRUK/Imago/issues/21 - example of an Issue for a long-term piece of work to be worked on later
https://github.com/Imago-SDRUK/Imago/pull/13 - example of a decent-sized PR with code review



---